# load colorscheme
run-shell ~/.config/tmux/tmux-srcery/srcery.tmux

#set -g default-terminal "tmux-256color"
#set-option -ga terminal-overrides ",xterm-256color:Tc"

# switch between panes vim-style
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# resize panes vim-style
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r H resize-pane -L 5
bind-key -r L resize-pane -R 5

# switch between windows vim-style
bind-key -r C-l select-window -t :+
bind-key -r C-h select-window -t :-
bind-key i last-window

# move window around
bind-key -r "<" swap-window -d -t -1
bind-key -r ">" swap-window -d -t +1

# split windows
bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "\\" split-window -fh -c "#{pane_current_path}"
bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fv -c "#{pane_current_path}"
bind-key "%" split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -v -c "#{pane_current_path}"

# number windows starting with 1 to line up with numbers on keyboard
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# vi-style navigation in copy mode
setw -g mode-keys vi

# monitor activity
setw -g monitor-activity on
set -g visual-activity off

# limit scrollback buffer
set -g history-limit 10000

# custom status right bar
#set -g status-right "#{prefix_highlight}#[fg=brightwhite,bg=$xgray3] %F %H:%M #{battery_color_fg}#[bg=$xgray3]#{battery_percentage} #[fg=brightwhite,bg=$xgray4,bold] #(whoami)@#h "

set -g @batt_color_charge_primary_tier8 green
set -g @batt_color_charge_primary_tier7 green
set -g @batt_color_charge_primary_tier6 green
set -g @batt_color_charge_primary_tier5 green
set -g @batt_color_charge_primary_tier4 green
set -g @batt_color_charge_primary_tier3 yellow
set -g @batt_color_charge_primary_tier2 red
set -g @batt_color_charge_primary_tier1 red
set -g @batt_color_charge_primary_tier0 red

# Left Statusline
set -g status-left-length 40

# Right Statusline
set -g status-right-length 150

# use C-a instead of C-b as prefix if within an ssh session
if-shell 'test -n "$SSH_CLIENT"' 'set -g prefix C-a'

# load plugins
run-shell ~/.config/tmux/tmux-sensible/sensible.tmux
run-shell ~/.config/tmux/tmux-prefix-highlight/prefix_highlight.tmux
#run-shell ~/.config/tmux/tmux-battery/battery.tmux

#set -g status-right "#{prefix_highlight}#[fg=brightwhite,bg=$xgray3] %F %H:%M #{battery_color_fg}#[bg=$xgray3]#{battery_percentage} #[fg=brightwhite,bg=$xgray4,bold] #(whoami)@#h "
