" load plugins
packadd rust
packadd swift
packadd syntastic

" colorscheme
colorscheme srcery

" tabs/spaces setup
set tabstop=4
set shiftwidth=2
set expandtab
set smarttab

" wrap long lines
set wrap
set linebreak

" keep three lines above/below cursor when scrolling
set scrolloff=3

" enable syntax highlighting in markdown code blocks.
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'rust', 'ruby', 'css', 'xml']

" hide some syntax chars
set conceallevel=3

" highlight words as you're searching for them.
set hlsearch
