" load plugins
packadd rust
packadd swift
"packadd syntastic
packadd ctrlp
packadd better-whitespace
packadd vala
packadd editorconfig
packadd meson
packadd base16-vim

" colorscheme
if filereadable(expand("~/.vimrc_background"))
  " let base16colorspace=256
  source ~/.vimrc_background
else
  colorscheme srcery
endif

" tabs/spaces setup
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

" wrap long lines
set wrap
set linebreak

" keep three lines above/below cursor when scrolling
set scrolloff=3

" enable syntax highlighting in markdown code blocks.
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'rust', 'ruby', 'css', 'xml', 'c']

" hide some syntax chars
set conceallevel=2

" highlight words as you're searching for them.
set hlsearch

" disable swap file creation
set noswapfile
